# Generated by Django 4.2.6 on 2023-11-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_roommember_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("Image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
