# Generated by Django 4.2.6 on 2023-11-26 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_faceimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faceimage",
            old_name="Image",
            new_name="image",
        ),
    ]
