# Generated by Django 4.2.6 on 2024-02-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_rename_image_faceimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=1000)),
                ("emotion", models.CharField(max_length=200)),
            ],
        ),
    ]
