# Generated by Django 4.2.6 on 2024-02-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student_Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=1000)),
                ("curious", models.IntegerField()),
                ("confusion", models.IntegerField()),
                ("frustration", models.IntegerField()),
                ("hopefullness", models.IntegerField()),
            ],
        ),
    ]
