# Generated by Django 4.2.6 on 2024-02-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_student_emotion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_emotion",
            name="confusion",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="student_emotion",
            name="curious",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="student_emotion",
            name="frustration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="student_emotion",
            name="hopefullness",
            field=models.IntegerField(default=0),
        ),
    ]
