# Generated by Django 4.2.6 on 2024-02-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_alter_student_emotion_confusion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_emotion",
            name="name",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
