# Generated by Django 4.2.6 on 2024-02-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_student_emotion_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("curious", models.CharField(max_length=5)),
                ("confusion", models.CharField(max_length=5)),
                ("frustration", models.CharField(max_length=5)),
                ("hopefullness", models.CharField(max_length=5)),
            ],
        ),
    ]
