# Generated by Django 4.2.6 on 2024-03-02 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_summary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student_emotion",
            old_name="frustration",
            new_name="boredom",
        ),
        migrations.RenameField(
            model_name="summary",
            old_name="frustration",
            new_name="boredom",
        ),
    ]
