# Generated by Django 4.2.6 on 2024-03-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_rename_frustration_student_emotion_boredom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_emotion",
            name="neutral",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="summary",
            name="neutral",
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
