# Generated by Django 4.2.6 on 2024-03-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_student_emotion_neutral_summary_neutral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="boredom",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="summary",
            name="confusion",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="summary",
            name="curious",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="summary",
            name="hopefullness",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="summary",
            name="neutral",
            field=models.FloatField(default=0.0),
        ),
    ]
