# Generated by Django 4.2.6 on 2024-03-05 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_alter_summary_boredom_alter_summary_confusion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="emotion",
        ),
        migrations.AddField(
            model_name="status",
            name="arousal",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="status",
            name="name",
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="status",
            name="time_stamp",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="status",
            name="valence",
            field=models.FloatField(default=0.0),
        ),
    ]
