# Generated by Django 4.2.6 on 2024-03-05 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_remove_status_emotion_status_arousal_status_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="status",
            old_name="time_stamp",
            new_name="time_stam",
        ),
    ]
