# Generated by Django 4.2.6 on 2024-03-05 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_rename_time_stamp_status_time_stam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="time_stam",
        ),
        migrations.AddField(
            model_name="status",
            name="time_stamp",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
