# Generated by Django 4.2.6 on 2024-03-05 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0017_alter_status_time_stamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="time_stamp",
            field=models.TimeField(
                default=datetime.datetime(
                    2024, 3, 5, 6, 30, 18, 850537, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
