# Generated by Django 4.2.6 on 2024-03-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_alter_status_time_stamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rankings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("curious_person", models.CharField(max_length=20)),
                ("confused_person", models.CharField(max_length=20)),
                ("bored_person", models.CharField(max_length=20)),
                ("hopefull_person", models.CharField(max_length=20)),
                ("neutral_person", models.CharField(max_length=20)),
            ],
        ),
    ]
