# Generated by Django 4.2.6 on 2024-03-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0021_rename_rankings_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranking",
            name="bored_person",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ranking",
            name="confused_person",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ranking",
            name="curious_person",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ranking",
            name="hopefull_person",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ranking",
            name="neutral_person",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ranking",
            name="rank",
            field=models.IntegerField(default=0),
        ),
    ]
