# Generated by Django 4.2.6 on 2024-03-05 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0022_alter_ranking_bored_person_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ranking",
        ),
    ]
