# Generated by Django 4.2.6 on 2024-03-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0023_delete_ranking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("curious_person", models.CharField(max_length=100)),
                ("confused_person", models.CharField(max_length=100)),
                ("bored_person", models.CharField(max_length=100)),
                ("hopefull_person", models.CharField(max_length=100)),
                ("neutral_person", models.CharField(max_length=100)),
            ],
        ),
    ]
