# Generated by Django 4.2.6 on 2024-03-05 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0024_ranking"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ranking",
        ),
    ]
