# Generated by Django 4.2.6 on 2024-03-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0025_delete_ranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="predicted_emotion",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
